---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/Users/aramide/nornir/DMVPN-RESTCONF-TEST/hosts.yaml"
        group_file: "/Users/aramide/nornir/DMVPN-RESTCONF-TEST/groups.yaml"
        defaults_file: "/Users/aramide/nornir/DMVPN-RESTCONF-TEST/defaults.yaml"
